---
title: "Assignment 4"
author: "Farhan"
date: "March 4, 2017"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Prerequisite of presentation

Your presentation must satisfy the following

1.  It must be done in Slidify or Rstudio Presenter
2.  It must be 5 pages
3.  It must be hosted on github or Rpubs
4.  It must contained some embedded R code that gets run when slidifying the document


## Your Reproducible Pitch

- Was the presentation completed in slidify or R Presenter?
- Was it 5 pages?
- Did it contain an R expression that got evaluated and displayed?
- Did it contain an R expression that got evaluated and displayed?
- Was it hosted on github or Rpubs?
- Was the server calculation displayed in the html page?

Here's your opportunity to give this presentation a +1 for being well done. Did they tinker around with the default style? Was the presentation particularly lucid and well organized? In other words, the student made a legitimate try.
There were no R errors displayed in the presentation.

## Your Shiny Application

- Was there enough documentation on the shiny site for a user to get started using the application?
- Did the application run as described in the documentation?
- Was there some form of widget input (slider, textbox, radio buttons, checkbox, ...) in either ui.R or a custom web page?
- Did server.R perform some calculations on the input in server.R?
- Was the server calculation displayed in the html page?
- Was the app substantively different than the very simple applications built in the class? 

Note, it's OK if the app is simple and based on the one presented in class. I just don't want it to be basically a carbon copy of the examples we covered. For example, if someone simply changed the variable names, then this would not count. However, a prediction algorithm that had a similar layout would be fine.
Here's your opportunity to give the app +1 for being well done, or neat, or even just a solid effort.

## Here shiny app

enclosed with this presentation with shiny app


apps: https://farhanr42.shinyapps.io/shinyapp/


 The shiny app show the no of computer in world from 1951 to 1961.
